lab02/calculadora/urls.py
from django.urls import path
from . import views

app_name = 'calculadora'
urlpatterns = [
    path('',views.index, name='index'),
    path('enviar',views.enviar, name="enviar"),
]

lab02/cilindro/urls.py
from django.urls import path
from . import views

app_name = 'cilindro'
urlpatterns = [
    path('',views.index, name='index'),
    path('enviar',views.enviar, name="enviar"),
]

lab02/encuesta/urls.py
from django.urls import path
from . import views
app_name = 'encuesta'
urlpatterns = [
    path('',views.index,name="index"),
    path('enviar',views.enviar,name="enviar"),
    
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('calculadora/',include('calculadora.urls')),
    path('cilindro/',include('cilindro.urls')),
    path('admin/', admin.site.urls),
    
]

lab02/calculadora/models.py
from django.db import models

# Create your models here.

lab02/cilindro/models.py
from django.db import models

# Create your models here.

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/calculadora/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context ={
        'titulo': "Bienvenido a mi calculadora",
    }
    return render(request, 'calculadora/calculadora.html',context)
def enviar(request):
    n1 = float(request.POST['numero1'] )
    n2 = float(request.POST['numero2'] )
    operacion = request.POST['operacion']
    if operacion == 'sumar':
        resultado = n1+n2
        simbolo = "+"
    elif operacion == 'restar':
        resultado = n1-n2
        simbolo = "-"
    elif operacion == 'multiplicar':
        resultado = n1*n2
        simbolo = "*"
    elif operacion == 'dividir':
        resultado = n1/n2
        simbolo = "/"
    context={
        'nombreoperacion' : request.POST['operacion'],
        'titulo' : "Respuesta",
        'numero1' : request.POST['numero1'],
        'simbolo' : simbolo,
        'numero2' : request.POST['numero2'],
        'respuesta' : resultado,
    }
    return render(request, 'calculadora/respuesta.html',context)

lab02/cilindro/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {
        'titulo' : "Calcular volumen del cilindro",
    }
    return render(request, 'cilindro/calcular.html',context)
def enviar(request):
    pi = 3.14159265359
    diametro = float(request.POST["diametro"])
    altura = float(request.POST["altura"])
    radio = diametro/2
    volumen = pi * (radio**2) * altura
    context ={
        'respuesta': volumen,
    }
    return render(request, 'cilindro/enviar.html',context)

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context ={
        "titulo" : "Formulario",
    }
    return render(request,"encuesta/formulario.html",context)
def enviar(request):
    context ={
        'titulo' : "Respuesta ",
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request,"encuesta/respuesta.html",context)

lab02/calculadora/templates/calculadora/calculadora.html
<h2>{{ titulo }}</h2>
<form action="{% url 'calculadora:enviar' %}" method="post">
    {% csrf_token %}
    Escriba el numero 1:
    <input type="text" name="numero1"> <br>
    Escriba el numero 2:
    <input type="text" name="numero2"> <br>
    Operacion:
    <select name="operacion" >
        <option value="sumar">suma</option>
        <option value="restar">resta</option>
        <option value="multiplicar">multiplicacion</option>
        <option value="dividir">division</option>
    </select> <br>
    <input type="submit" name="submit" value="Enviar">





</form>

lab02/calculadora/templates/calculadora/respuesta.html
<h2>{{ titulo }}</h2>
<p> {{ nombreoperacion }}   {{numero1}} {{ simbolo }} {{ numero2 }} = {{ respuesta }}</p>

lab02/cilindro/templates/cilindro/calcular.html
<h2>{{ titulo }}</h2>
<form action="{% url 'cilindro:enviar' %}" method="post">
    {% csrf_token %}
    Introduzca el diametro en metros:
    <input type="text" name="diametro"><br><br>
    Introduzca la altura en metros:
    <input type="text" name="altura"><br><br>
    <input type="submit" name="submit" value="Enviar">
</form>

lab02/cilindro/templates/cilindro/enviar.html
<p> El volumen del cilindro es de {{ respuesta }} metros cubicos</p>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="POST">
{% csrf_token %}

Hombre:
<input type="text" name= "nombre" maxlength="50"><br>
Contraseña:
<input type="password" name="password"><br>
Educacion:

<select name="educacion">
<option value="sin-estudios">Sin estudios</option>
<option value="educacion-obligatoria" selected="selected">Educación Obligatoria</option>
<option value="formacion-profesional"> Formación profesional</option>
<option value="universidad">Universidad</option>

</select> <br>

Nacionalidad:

<input type="radio" name="nacionalidad" value="hispana">Hispana</input>
<input type="radio" name="nacionalidad" value="otra">Otra</input><br>

Idiomas:
<input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
<input type="checkbox" name="idiomas" value="ingles" >Inglés</input>
<input type="checkbox" name="idiomas" value="francés" >Francés</input>
<input type="checkbox" name="idiomas" value="aleman" >Alemán</input><br>
Email:
<input type="text" name="email"><br>
Sitio Web:
<input type="text" name="sitioweb"><br>
<input type="submit" name="submit" value="Enviar"><br>
</form>

lab02/encuesta/templates/encuesta/respuesta.html
<h1>{{ titulo }}</h1>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas: </p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email : {{ correo }}</p>
<p>Sitio Web: {{ website }}</p>